# Maintainer: Joel Hanger <joel@tacitsoft.dev>
# Contributor: Joel Hanger <joel@tacitsoft.dev>
#
# sha512sums is left empty here; CI regenerates it via `abuild checksum`
# before building (the tarball is created from `git archive` in CI).
# For local builds, populate it with: abuild checksum

pkgname=xmms
pkgver=1.3.0
pkgrel=0
pkgdesc="X Multimedia System — classic Winamp-style audio player (GTK3 resurrection)"
url="https://github.com/tacitness/xmms"
arch="all"
license="GPL-2.0-or-later"

depends="gtk+3.0 glib"
makedepends="
cmake
ninja
pkgconf
gtk+3.0-dev
glib-dev
cairo-dev
alsa-lib-dev
pulseaudio-dev
libvorbis-dev
libogg-dev
mpg123-dev
flac-dev
libx11-dev
libxext-dev
libxxf86vm-dev
gettext-dev
desktop-file-utils
"

subpackages="$pkgname-dev:dev $pkgname-alsa $pkgname-pulse"

source="$pkgname-$pkgver.tar.gz::https://github.com/tacitness/xmms/archive/refs/tags/v$pkgver.tar.gz"
builddir="$srcdir/xmms-$pkgver"

# sha512sums regenerated by CI via `abuild checksum` from the git-archive tarball
sha512sums=""

build() {
	# musl libc doesn't transitively include unistd.h/string.h like glibc does;
	# force-include them so legacy POSIX calls resolve without touching ~100 files.
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DCMAKE_C_FLAGS="-include unistd.h -include string.h -Wno-cast-function-type" \
		-DXMMS_GTK_VERSION=3 \
		-DXMMS_ENABLE_ALSA=ON \
		-DXMMS_ENABLE_PULSE=ON
	cmake --build build
}

check() {
	# No automated test suite yet (tracked in issue #28)
	:
}

package() {
	DESTDIR="$pkgdir" cmake --install build
}

post_install() {
	# Refresh icon cache and desktop db so the app appears in launchers
	/usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
	/usr/bin/update-desktop-database -q /usr/share/applications || true
}

post_upgrade() {
	post_install
}

dev() {
	default_dev
}

alsa() {
	pkgdesc="XMMS — ALSA output plugin"
	depends="$pkgname=$pkgver-r$pkgrel alsa-lib"
	amove usr/lib/xmms/Output/ALSA.so
}

pulse() {
	pkgdesc="XMMS — PulseAudio output plugin"
	depends="$pkgname=$pkgver-r$pkgrel pulseaudio-libs"
	amove usr/lib/xmms/Output/Pulse.so
}
