# Maintainer: XMMS Resurrection Team <xmms-dev@example.com>
# Contributor: XMMS Resurrection Team <xmms-dev@example.com>
#
# sha512sums is left empty here; CI regenerates it via `abuild checksum`
# before building (the tarball is created from `git archive` in CI).
# For local builds, populate it with: abuild checksum

pkgname=xmms
pkgver=1.3.0
pkgrel=0
pkgdesc="X Multimedia System — classic Winamp-style audio player (GTK3 resurrection)"
url="https://github.com/tacitness/xmms"
arch="all"
license="GPL-2.0-or-later"

depends="gtk+3.0 glib"
makedepends="
cmake
ninja
pkgconf
gtk+3.0-dev
glib2-dev
cairo-dev
alsa-lib-dev
pulseaudio-dev
libvorbis-dev
libogg-dev
mpg123-dev
flac-dev
libx11-dev
libxext-dev
libxxf86vm-dev
gettext-dev
desktop-file-utils
"

subpackages="$pkgname-dev:dev $pkgname-doc:doc $pkgname-alsa $pkgname-pulse"

source="$pkgname-$pkgver.tar.gz::https://github.com/tacitness/xmms/archive/refs/tags/v$pkgver.tar.gz"
builddir="$srcdir/xmms-$pkgver"

# sha512sums regenerated by CI via `abuild checksum` from the git-archive tarball
sha512sums=""

build() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DXMMS_GTK_VERSION=3 \
		-DXMMS_ENABLE_ALSA=ON \
		-DXMMS_ENABLE_PULSE=ON
	cmake --build build
}

check() {
	# No automated test suite yet (tracked in issue #28)
	:
}

package() {
	DESTDIR="$pkgdir" cmake --install build
}

post_install() {
	# Refresh icon cache and desktop db so the app appears in launchers
	/usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
	/usr/bin/update-desktop-database -q /usr/share/applications || true
}

post_upgrade() {
	post_install
}

dev() {
	default_dev
	amove usr/share/aclocal/xmms.m4
}

doc() {
	default_doc
}

alsa() {
	pkgdesc="XMMS — ALSA output plugin"
	depends="$pkgname=$pkgver-r$pkgrel alsa-lib"
	amove usr/lib/xmms/Output/libALSA*
}

pulse() {
	pkgdesc="XMMS — PulseAudio output plugin"
	depends="$pkgname=$pkgver-r$pkgrel pulseaudio-libs"
	amove usr/lib/xmms/Output/libpulse*
}
