/* GTK - The GIMP Toolkit
 * Copyright (C) 1995-1997 Peter Mattis, Spencer Kimball and Josh MacDonald
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

/*
 * Modified by the GTK+ Team and others 1997-1999.  See the AUTHORS
 * file for a list of people on the GTK+ Team.  See the ChangeLog
 * files for a list of changes.  These files are distributed with
 * GTK+ at ftp://ftp.gtk.org/pub/gtk/.
 */

/* GTK3: rewritten using G_DECLARE_FINAL_TYPE (GTK2 GtkTypeInfo system removed) */
#ifndef XMMS_ENTRY_H
#define XMMS_ENTRY_H

#include <gtk/gtk.h>

G_BEGIN_DECLS

/* GTK3: XMMS_TYPE_ENTRY, XMMS_ENTRY(), XMMS_IS_ENTRY() generated by G_DECLARE_FINAL_TYPE */
#define XMMS_TYPE_ENTRY (xmms_entry_get_type())

    G_DECLARE_FINAL_TYPE(XmmsEntry, xmms_entry, XMMS, ENTRY, GtkEntry)

    GtkWidget *xmms_entry_new(void);

G_END_DECLS

#endif /* XMMS_ENTRY_H */
