/* cmake/xmms_config.h.cmake — generated by CMake, do not edit directly */
/* Mirrors the autoheader-generated config.h */

#ifndef XMMS_CONFIG_H
#define XMMS_CONFIG_H

/* GTK version being built against */
#cmakedefine XMMS_GTK3 1
#cmakedefine XMMS_GTK4 1

/* Audio output plugins available */
#cmakedefine HAVE_ALSA 1
#cmakedefine HAVE_OSS  1
#cmakedefine HAVE_ESD  1

/* Input plugins / codec libraries */
#cmakedefine HAVE_LIBMPG123  1
#cmakedefine HAVE_VORBIS     1
#cmakedefine HAVE_OGG        1
#cmakedefine HAVE_FLAC       1
#cmakedefine HAVE_MIKMOD     1
#cmakedefine HAVE_CDAUDIO    1

/* X11 session management */
#cmakedefine WITH_SM 1

/* XF86VidMode extension */
#cmakedefine XF86VIDMODE 1

/* Per-user plugin directory (can be disabled) */
#cmakedefine DISABLE_USER_PLUGIN_DIR 1

/* i386 assembly optimisations in mpg123 */
#cmakedefine ARCH_X86   1
#cmakedefine USE_X86ASM 1
#cmakedefine USE_SIMD   1

/* libESD latency function */
#cmakedefine HAVE_ESD_GET_LATENCY 1

/* Install paths (set by CMake) */
#define DATA_DIR    "@XMMS_DATA_DIR@"
#define PLUGIN_DIR  "@XMMS_PLUGIN_BASE_DIR@"
#define LOCALEDIR   "@XMMS_LOCALE_DIR@"

/* Package metadata */
#define PACKAGE          "@PROJECT_NAME@"
#define VERSION          "@PROJECT_VERSION@"
#define RELEASE_NAME     "@XMMS_RELEASE_NAME@"
#define RELEASE_AUTHOR   "@XMMS_RELEASE_AUTHOR@"

#endif /* XMMS_CONFIG_H */
